<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Pay Now</name>
   <tag></tag>
   <elementGuidId>621a40d6-a51b-421a-a681-9d4b190db0ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='redesign-v15-cta']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#redesign-v15-cta</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>34093d49-fc80-411d-a959-770771aaad01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>redesign-v15-cta</value>
      <webElementGuid>ee4d3807-59f8-4416-a001-152ff1bffa84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>svelte-13mgn3i</value>
      <webElementGuid>f114a929-5bbf-4ac8-bc63-1f004efcf418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pay Now</value>
      <webElementGuid>04a1a8bc-3b5c-4b9c-bc6e-1f529b4d9afd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;redesign-v15-cta&quot;)</value>
      <webElementGuid>9474f445-5f66-4fd6-9613-08b7670aff32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/recording_objects/Page_Narayana Health - Payment Link - LUBwz_272e9e/iframe_Narayana Health_razorpay-checkout-frame</value>
      <webElementGuid>276d1407-f285-4216-9e03-4e0665536d6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='redesign-v15-cta']</value>
      <webElementGuid>f1f57c74-8b9a-4c80-b6f2-1a6b36dd8b45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div[4]/div[2]/button</value>
      <webElementGuid>b389573f-9ce8-452a-a6ca-9d55aa16de26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Details'])[1]/following::button[1]</value>
      <webElementGuid>5a4d274a-6d3b-4a4c-b874-f83733a0c34a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹ 1,050'])[2]/following::button[2]</value>
      <webElementGuid>d2dcc4ac-af3d-4aa2-af5a-af91ec7ba535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/preceding::button[2]</value>
      <webElementGuid>da5bad35-1721-4e20-9c15-ef3495e13323</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pay Now']/parent::*</value>
      <webElementGuid>7ba15cde-36f8-41b3-8bec-88481fb4620d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>720e6e6d-9184-4a6c-9a4f-5f60a282bcba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'redesign-v15-cta' and (text() = 'Pay Now' or . = 'Pay Now')]</value>
      <webElementGuid>d4d186a0-3c9e-4725-9038-e90858f4f16b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
