<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Proceed</name>
   <tag></tag>
   <elementGuidId>3af32b4a-59a6-42d6-93f8-81a2278f151b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='redesign-v15-cta']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#redesign-v15-cta</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>111b75d9-fd94-415e-9880-653fe213893f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>redesign-v15-cta</value>
      <webElementGuid>52135bab-8ad6-4338-8c98-87e736a1d4cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>svelte-13mgn3i</value>
      <webElementGuid>0ce38cc7-b731-495e-b7a0-6f500692de20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Proceed</value>
      <webElementGuid>6e1d57ea-9d4e-43e1-abf3-7a88117cc620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;redesign-v15-cta&quot;)</value>
      <webElementGuid>9d747b4e-5e05-4786-92d9-4b6a3a2be67c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/recording_objects/Page_Narayana Health - Payment Link - LUBwz_272e9e/iframe_Narayana Health_razorpay-checkout-frame</value>
      <webElementGuid>5e409638-5c53-4f55-9aee-ef78cfe2bb85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='redesign-v15-cta']</value>
      <webElementGuid>6a219b15-97c1-4561-8936-78630475d86d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div[4]/div/button</value>
      <webElementGuid>a72acb96-b489-4b4b-90b3-7ea6d8ce5081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading currencies...'])[2]/following::button[1]</value>
      <webElementGuid>745ace1b-707a-4fa9-ac73-2dfe9ca40e24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading currencies...'])[1]/following::button[1]</value>
      <webElementGuid>4df6d7b4-a528-4b01-bf85-4fdc5aa2ec8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/preceding::button[2]</value>
      <webElementGuid>b3505a7c-dd5e-4297-a490-0c5410bcdc89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Proceed']/parent::*</value>
      <webElementGuid>c823830f-49f6-4cc7-a1dd-7c2d3acc12e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/button</value>
      <webElementGuid>3422c8c9-efd0-45b1-8ce4-938de58acc9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'redesign-v15-cta' and (text() = 'Proceed' or . = 'Proceed')]</value>
      <webElementGuid>1e02cc85-ced6-4a2a-ac8a-f0b9fd3e7a69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
