<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Narayana Health_razorpay-checkout-frame</name>
   <tag></tag>
   <elementGuidId>24004440-d664-40c0-b2bb-1f19efd39370</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='checkout-parent']/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe.razorpay-checkout-frame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>0660fb76-e39a-4580-90b4-91f6eeeaad08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c4ab9006-0915-4a5d-8e15-bd319ceb4214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>eb7ac33f-645b-4e53-bf43-3e8f5538b8f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>b216fb6c-007d-48a6-a535-8022a4e3f345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>1ec26d1a-cea8-46c2-85ac-bbf2b7b7c9d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowpaymentrequest</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1be453c7-8458-41f2-a53a-6376435efd7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://api.razorpay.com/v1/checkout/public?traffic_env=baseline&amp;build=3b28a787e01f62916e862f4566f43d2092753d66</value>
      <webElementGuid>6989c206-0678-4309-96c9-951516224817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>razorpay-checkout-frame</value>
      <webElementGuid>d2cbd38d-a8c6-4793-98a1-96030700ddea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout-parent&quot;)/iframe[@class=&quot;razorpay-checkout-frame&quot;]</value>
      <webElementGuid>4b92f4ec-a6af-4466-9863-0b24ff4ccf43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-parent']/iframe</value>
      <webElementGuid>1d4b8c64-cb29-4cd2-8577-e08a17a68a5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>be7936cc-61bd-474e-8771-b41dee527a48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://api.razorpay.com/v1/checkout/public?traffic_env=baseline&amp;build=3b28a787e01f62916e862f4566f43d2092753d66']</value>
      <webElementGuid>53c94711-4465-440c-b06a-4068dc7fa8a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
