<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Narayana Health_razorpay-checkout-frame</name>
   <tag></tag>
   <elementGuidId>a49be5fc-8249-49a2-b761-69c9cd6b2cfd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='checkout-parent']/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe.razorpay-checkout-frame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>3b743b7e-4764-4276-a2a1-dfcdbd8f9091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d89c110a-4568-4b54-a518-34d36a791c1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e11d09d3-e5cb-4a90-9f05-43ec9804af66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>790efa44-3059-4093-bfc4-8fcd58363a3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>55747e0e-ed4f-4c38-8ac5-68e001cf088e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowpaymentrequest</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dd199b6d-346d-4d74-a968-617ea2ca2390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://api.razorpay.com/v1/checkout/public?traffic_env=production&amp;build=3b28a787e01f62916e862f4566f43d2092753d66</value>
      <webElementGuid>c87119be-996c-4706-a82c-29603e07f04a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>razorpay-checkout-frame</value>
      <webElementGuid>c0658444-8c80-49e4-af12-d9c63cac5ef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout-parent&quot;)/iframe[@class=&quot;razorpay-checkout-frame&quot;]</value>
      <webElementGuid>aa33041d-661b-409a-b9c7-65a42b6ac076</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-parent']/iframe</value>
      <webElementGuid>41fa6a8d-8b51-429e-bbcc-62502851b719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>0d5845cc-f6c7-42f0-a57b-0d148c1b7a19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://api.razorpay.com/v1/checkout/public?traffic_env=production&amp;build=3b28a787e01f62916e862f4566f43d2092753d66']</value>
      <webElementGuid>05aacf40-2279-4f55-87cf-f9fd39867379</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
