<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continue</name>
   <tag></tag>
   <elementGuidId>35b301c7-650d-4fe3-9a28-5816cbaa13c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ocapp-body']/app-book-appointment/div/section/article[2]/div[2]/div[2]/div[3]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.portal-primary-btn.appointment-primary-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3dc6a0cd-f794-4757-90c7-ed4e0ee21e86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>portal-primary-btn appointment-primary-btn</value>
      <webElementGuid>f82055cf-e624-494f-9cf8-5916471b2e9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>99b2d2c2-ef8d-49a6-92fe-779689f1f4f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ocapp-body&quot;)/app-book-appointment[1]/div[@class=&quot;main-container ps ps--active-y&quot;]/section[@class=&quot;appointment-grid&quot;]/article[@class=&quot;slot book-appointment-row&quot;]/div[@class=&quot;slots-selection-container&quot;]/div[@class=&quot;available-slots-container footer-added&quot;]/div[@class=&quot;button-container fixed-footer&quot;]/button[@class=&quot;portal-primary-btn appointment-primary-btn&quot;]</value>
      <webElementGuid>3e102947-c5bc-4e2d-9ae0-470250e263e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ocapp-body']/app-book-appointment/div/section/article[2]/div[2]/div[2]/div[3]/button</value>
      <webElementGuid>ac7c3256-d492-402c-9df5-6ea828174e08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::button[42]</value>
      <webElementGuid>954359db-dd28-4e6f-a209-ca6e97553ef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mon'])[1]/following::button[43]</value>
      <webElementGuid>0cbddf6d-f7f1-4ccf-897d-3ff477f4b4d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue']/parent::*</value>
      <webElementGuid>811acc20-66ae-49c0-94c9-31450b0b879d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>96fff6c7-3efb-4b1b-9c8a-01264644b09b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>e5e2ed62-90e4-47c3-9d2d-243ac9497d06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
