<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_745 PM</name>
   <tag></tag>
   <elementGuidId>951e36c9-6703-4644-8b9f-ac6f395a8384</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ocapp-body']/app-book-appointment/div/section/article[2]/div[2]/div[2]/div/div[2]/button[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bfe86c90-2cf3-4dd3-9171-e6dba29e36a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slot</value>
      <webElementGuid>fc168a1c-c2cb-4f4c-851c-7a39c69923c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 7:45 PM </value>
      <webElementGuid>3f0ecd1e-c29d-44d5-aad8-0b8dc452620c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ocapp-body&quot;)/app-book-appointment[1]/div[@class=&quot;main-container ps ps--active-y&quot;]/section[@class=&quot;appointment-grid&quot;]/article[@class=&quot;slot book-appointment-row&quot;]/div[@class=&quot;slots-selection-container&quot;]/div[@class=&quot;available-slots-container footer-added&quot;]/div[@class=&quot;slot-session evening-slots&quot;]/div[@class=&quot;slots&quot;]/button[@class=&quot;slot&quot;]</value>
      <webElementGuid>a4db2bef-08f3-457b-958d-18d1405cb94c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ocapp-body']/app-book-appointment/div/section/article[2]/div[2]/div[2]/div/div[2]/button[3]</value>
      <webElementGuid>617b34ed-84ac-4783-94d3-39dbbff8988c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::button[3]</value>
      <webElementGuid>b14184a9-31c9-47d2-8e60-a9096f9234d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mon'])[1]/following::button[4]</value>
      <webElementGuid>51bc9516-fa67-43b8-831b-8906f89582eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue'])[1]/preceding::button[39]</value>
      <webElementGuid>896266c2-7205-44c5-94c4-ba9d965889be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='7:45 PM']/parent::*</value>
      <webElementGuid>a4f76a91-6d04-4e09-8449-02a116abc9d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>0d7fedc2-9ece-4aba-8744-1fd8f3205020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' 7:45 PM ' or . = ' 7:45 PM ')]</value>
      <webElementGuid>390e0811-c06f-4680-8dec-f1bafa06c835</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
