<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Verify OTP_loginOtpdigit1</name>
   <tag></tag>
   <elementGuidId>330bc546-804f-4f5d-8676-80bbf1c6cd62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='loginOtpdigit1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#loginOtpdigit1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f5d3ef6c-b613-4099-849a-cb2d3518aae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>a724abfd-39c4-4853-aa3f-caa785b603af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loginOtpdigit1</value>
      <webElementGuid>ab93fd09-d0ac-4d58-8331-4381bfc547ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>loginOtpdigit1</value>
      <webElementGuid>a73d451f-4f71-4c0e-b552-c178bcbec511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7708f4ba-827d-4a7b-8be1-1a20ead3d88a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>87048442-4400-4427-a2da-d22ffc4ea60b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-touched ng-dirty ng-valid</value>
      <webElementGuid>a0dd4374-0d68-47e2-9c5a-a627ee9ef2ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginOtpdigit1&quot;)</value>
      <webElementGuid>79dde98e-83ce-4bf4-bc11-659c4a039be8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='loginOtpdigit1']</value>
      <webElementGuid>78048945-0b13-4246-b2e9-ac09dcebfaa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>746bac3f-3bc2-48ad-9e56-3a223b8abadb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'loginOtpdigit1' and @name = 'loginOtpdigit1']</value>
      <webElementGuid>b542f8f5-5ec9-4f03-8a00-6223a1a0aefe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
