<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Verify OTP_loginOtpdigit6</name>
   <tag></tag>
   <elementGuidId>970d2425-b832-4782-acdb-eed2f428741e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='loginOtpdigit6']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#loginOtpdigit6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f1774692-4fb4-4e7b-8a0e-0b5a0f8cf70a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>82fe1d86-9f3b-46e8-96ed-2a031bae476f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loginOtpdigit6</value>
      <webElementGuid>4ae3cb70-75bd-44c4-9ea6-ab7714b82eef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>loginOtpdigit6</value>
      <webElementGuid>ff5045ca-c473-45e9-8ebc-049eac1a0840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9f7b464b-3262-4913-9e23-9d66b9a22a39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>34b68b07-e6d3-471d-8fe6-ab14a8d0f3bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-dirty ng-valid</value>
      <webElementGuid>0d02da20-b856-4bdb-a426-77b009df25df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginOtpdigit6&quot;)</value>
      <webElementGuid>f21f3864-7649-4d4f-8dd9-4ccbb94f5cc5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='loginOtpdigit6']</value>
      <webElementGuid>4bd013fc-fe2d-4022-b403-91b202477d5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[6]</value>
      <webElementGuid>f98bdee5-b03b-4105-ac20-e8a2ac676aec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'loginOtpdigit6' and @name = 'loginOtpdigit6']</value>
      <webElementGuid>6368e30a-ccc7-4243-9525-b8defe4fa6c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
