<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Visakhapatnam_header-input-search-bar_5b2ba0</name>
   <tag></tag>
   <elementGuidId>9af96f76-44f8-49b2-badc-e72e5d81bdb7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.header-input-search-bar.ng-untouched.ng-valid.ng-dirty</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2be3f66e-fd6c-4239-9bdf-ebaa5f98fc4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>981cd677-acb6-4477-910f-1fa332ec7f9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header-input-search-bar ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>f212e455-48f4-4a45-b956-8ddadc7ddcb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search by doctors, speciality, symptom or hospital</value>
      <webElementGuid>cf15e459-cc77-4db5-b530-a4af4cdfa569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-nav-bar&quot;)/div[@class=&quot;header-content&quot;]/div[@class=&quot;web-header&quot;]/nav[1]/div[@class=&quot;py-2 d-flex main-search&quot;]/div[@class=&quot;search-container row m-0 header-search-container&quot;]/app-search-bar[@class=&quot;col-md-6 p-0&quot;]/div[@class=&quot;input-container p-0 position-relative header-input-container&quot;]/input[@class=&quot;header-input-search-bar ng-untouched ng-valid ng-dirty&quot;]</value>
      <webElementGuid>6b071e7c-2d58-47ae-be1d-d9d61a8e8748</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>9a0e36dd-e958-41d9-bcdf-60843f1e3d23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header-nav-bar']/div/div/nav/div/div/app-search-bar/div/input</value>
      <webElementGuid>5dd08bbb-5f28-46e4-b2c5-72102af8e7a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>9fce9784-3bd9-43aa-be88-eaa90f0a5592</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Search by doctors, speciality, symptom or hospital']</value>
      <webElementGuid>bbf89c5b-4fe6-4951-a683-0003993444cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
