<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__patientPincode</name>
   <tag></tag>
   <elementGuidId>c4bfca4b-2a30-4712-9055-9e831a38e814</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='patientPincode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;patientPincode&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dd3aba32-f46f-4142-ba60-86d74be81fa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ced6a0f3-ef58-4d40-9703-d8c2807717d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>patientPincode</value>
      <webElementGuid>37376662-4a24-42dc-8c94-3f16e327c590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter pincode</value>
      <webElementGuid>6acf1943-ffe9-4635-98fa-a3cc44a7ef3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>zipCode</value>
      <webElementGuid>48a82cf7-f03e-408f-819b-865c710816ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>7f0bad75-0df0-4a0f-8b66-9de7ca530dbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>ebd2d53c-635d-4091-ac2e-2bd1caa7ca04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>0fcdf5fa-3a81-4bbf-98ff-6d969cfb2224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modal-open&quot;]/modal-container[@class=&quot;modal fade show&quot;]/div[@class=&quot;modal-dialog modal-dialog-centered patient-details-window&quot;]/div[@class=&quot;modal-content&quot;]/app-patient-details[1]/div[@class=&quot;modal-body portal-modal-body&quot;]/form[@class=&quot;patient-details-form ng-invalid ng-dirty ng-touched&quot;]/div[@class=&quot;row form-row&quot;]/div[@class=&quot;form-group col-3&quot;]/input[@class=&quot;form-control ng-untouched ng-pristine ng-invalid&quot;]</value>
      <webElementGuid>beae57b0-1c12-45c4-addc-ae712b693027</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='patientPincode']</value>
      <webElementGuid>7d686581-f008-4dc4-bcdf-feb2f6e0ed7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/input</value>
      <webElementGuid>87008dc2-e9bf-4209-9f43-9a4374c74d76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'patientPincode' and @placeholder = 'Enter pincode']</value>
      <webElementGuid>9bd39be1-aa56-4f60-b7c9-a7904d958fc8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
