<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__icon-portal_calender</name>
   <tag></tag>
   <elementGuidId>7d16714d-39ab-41ec-be17-8c0a812d47b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='dobAppend']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dobAppend > span.icon-portal_calender</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>06d0a9a1-87c3-4961-bd01-d7cfc35f9bb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-portal_calender</value>
      <webElementGuid>fd32efff-0939-4fc4-ae04-d9da0b05e266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dobAppend&quot;)/span[@class=&quot;icon-portal_calender&quot;]</value>
      <webElementGuid>f282e8cc-d168-46a6-b339-700bdd17e775</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='dobAppend']/span</value>
      <webElementGuid>00d6dc81-1566-4a4c-be34-7db80cc8ed6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/button/span</value>
      <webElementGuid>6793c3db-536e-4402-8f7a-f5252ae8ed9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
