<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>//button[contains(text(),'Reschedule')]</description>
   <name>reschedule_button</name>
   <tag></tag>
   <elementGuidId>52f06796-8a77-4eae-9bf6-89ccd0100aee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[contains(text(),'Reschedule')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
