<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>//input[@id='loginOtpdigit3']</description>
   <name>otp_field3</name>
   <tag></tag>
   <elementGuidId>d8b27c29-9501-480a-91a7-02ce2587b094</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='loginOtpdigit3']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
